name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
  runs_on: ubuntu-latest
  steps:
    - users: actions/checkout@v3
    - name: Build and push docker image
      run: |
        docker login --username ankur1812 --password ${{secrets.GHCR_ACCESS_TOKEN}}
        docker build . --tag ghcr.io/ankur1812/hello-world-ghcr:latest
        docker push ghcr.io/ankur1812/hello-world-ghcr:latest
